### ISSUE TITLE
Support for Asterisk 14 and newer CLI commands

### ISSUE THREAD

**Issue by roelvanmeer** [clue/reactphp-ami#50]
The output of commands has changed in Asterisk 14. The result of a CLI command is now shown in lines prefixed with "Output:".
This causes problems when using php-ami-react with newer versions of Asterisk. When a command is executed, the response is:

```
Error executing "DeviceStateList": Error "Command output follows"
```

which is because the actual Asterisk output looks like this:

```
Action: Command
Command: sip show user example

Response: Success
Message: Command output follows
Output: User example not found.
Output: 

```

The relevant Asterisk commit where this is described is https://github.com/asterisk/asterisk/commit/2f418c052ec

**Comment by clue** [comment]
@roelvanmeer Thanks for reporting this! I'm glad Asterisk finally cleaned up this legacy leftover, the new format makes a lot more sense.

It's my understanding executing the command still works just fine with newer Asterisk versions, but `getCommandOutput()` may return `null`? If so, we just have to update this to return the concatenated output of `getFieldValues('Output')` when the legacy format is not in use.

Can you confirm this?

**Comment by roelvanmeer** [comment]
@clue Yes, that seems to be correct.
