### ISSUE TITLE
Error in generics

### ISSUE THREAD

**Issue by thomasvargiu** [clue/reactphp-ami#56]
In client methods [generics](
https://github.com/clue/reactphp-ami/commit/a1eb1f241bd52087830f143a13de19f0d2ce6f93#diff-ad894315862be03731679203fb9b25acR31) for `PromiseInterface` are wrong:

```php
/**
 * @return \React\Promise\PromiseInterface<Response,\Exception>
 */
```

`Response` is not in the same namespace so it referers to an not existing class.

**Comment by clue** [comment]
The same file uses the following import:

```php
use Clue\React\Ami\Protocol\Response;
```

Do you feel anything's missing here?

**Comment by thomasvargiu** [comment]
You're right, give me some time to check why [phpstan](https://github.com/phpstan/phpstan) didn't recognize it in my project.

**Comment by thomasvargiu** [comment]
Sorry, the problem is in the [`Client`](https://github.com/clue/reactphp-ami/commit/a1eb1f241bd52087830f143a13de19f0d2ce6f93#diff-ff73e042e738204c6da009e2ed19f783R80) class for the `request()` method.
