### ISSUE TITLE
Authentication fails if username/password contains characters that need to be URL encoded

### ISSUE THREAD

**Issue by bennnjamin** [clue/reactphp-ami#62]
Hello, when connecting to AMI using credentials that contain special characters like !@#$%^&*() authentication fails. When you encode the characters using ```urlencode```, the URL is parsed properly by PHP, but this library does not decode the username and password before sending the login request over the AMI connection, so authentication fails.

https://github.com/clue/reactphp-ami/blob/master/src/Factory.php#L101

Solution:

Add ```urldecode``` to user and pass: https://github.com/clue/reactphp-ami/blob/master/src/Factory.php#L119

**Comment by clue** [comment]
@bennnjamin Thanks for reporting, it does indeed look like #63 fixes this bug! :+1:
