### ISSUE TITLE
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Clue\React\Ami\Factory::__construct(), 0 passed in

### ISSUE THREAD

**Issue by soap** [clue/reactphp-ami#72]
I have tried to run event.php example code. But the following error occurred.

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Clue\React\Ami\Factory::__construct(), 0 passed in....

Is it still working? I use PHP 7.4 on Windows 10.

**Comment by SimonFrings** [comment]
Hi @soap, I don't know for sure but I think you're installing the current v1.1.0 of ami. This version doesn't support the new eventloop implementation. We're planning a new v1.2.0 which will be released in a couple days.
Until then just install the current developer version: `clue/reactphp-ami": "dev-main",`

**Comment by soap** [comment]
Thanks @SimonFrings  It is working now.

**Comment by SimonFrings** [comment]
@soap To keep you updated, I have just released version 1.2.0 of clue/reactphp-ami. You can start using the new version as of today :+1:

**Comment by soap** [comment]
Ok I will try it. Thanks for information.
